// Generated by CoffeeScript 1.6.2
(function() {
  define(function(require, exports, module) {
    var ASObject, jasmine;
    jasmine = require('jasmine');
    ASObject = require('content/AS.content');
    return describe('ASObject', function() {
      var mockHtml;
      mockHtml = '<p>Content</p>';
      beforeEach(function() {
        console.log(ASObject);
        return this.asObject = new ASObject(mockHtml);
      });
      it('fails to set .html because html is derived', function() {
        var originalHtml, resultOfSet;
        originalHtml = this.asObject.html();
        resultOfSet = this.asObject.html('woah');
        expect(resultOfSet).toBe(false);
        return expect(this.asObject.html()).toBe(originalHtml);
      });
      it('gets html when .html is called', function() {
        return expect(this.asObject.html()).toBe(mockHtml);
      });
      return it('has a .content method that returns the HTML content', function() {
        return expect(this.asObject.content()).toBe(mockHtml);
      });
    });
  });

}).call(this);

/*
//@ sourceMappingURL=AS.content.map
*/
