// Generated by CoffeeScript 1.6.2
(function() {
  define(function(require, exports, module) {
    var Triptych, jasmine;
    jasmine = require('jasmine');
    Triptych = require('content/triptych.content');
    return describe('Triptych', function() {
      beforeEach(function() {
        return this.trip = new Triptych('1', '2', '3');
      });
      it('fails to set .html because html is derived', function() {
        var originalHtml, resultOfSet;
        originalHtml = this.trip.html();
        resultOfSet = this.trip.html('woah');
        expect(resultOfSet).toBe(false);
        return expect(this.trip.html()).toBe(originalHtml);
      });
      return it('gets html when .html is called', function() {
        return expect(this.trip.html()).toBe('1 - 2 - 3');
      });
    });
  });

}).call(this);

/*
//@ sourceMappingURL=triptych.content.map
*/
