// Generated by CoffeeScript 1.6.2
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(function(require, exports, module) {
    var ASObject, Content;
    Content = require('content');
    ASObject = (function(_super) {
      __extends(ASObject, _super);

      function ASObject(html) {
        this.content(html);
      }

      ASObject.prototype.html = function(newVal) {
        if (newVal) {
          console.log("Warning: Can't set .html on ASObject. It is derived");
          return false;
        }
        return this.content();
      };

      ASObject.prototype.content = function(newHtml) {
        if (!newHtml) {
          return this._content;
        }
        if (typeof newHtml !== 'string') {
          throw "ASObject::content must be passed a String of HTML";
        }
        return this._content = newHtml;
      };

      return ASObject;

    })(Content);
    return exports = ASObject;
  });

}).call(this);

/*
//@ sourceMappingURL=AS.content.map
*/
