// Generated by CoffeeScript 1.6.2
(function() {
  define(function(require, exports, module) {
    var Content;
    Content = (function() {
      function Content(html) {
        this.html(html);
      }

      Content.prototype.html = function(newHtml) {
        if (!newHtml) {
          return this._html;
        }
        if (typeof newHtml !== 'string') {
          throw "Content::html must be passed a String of HTML";
        }
        return this._html = newHtml;
      };

      Content.prototype.toString = function() {
        return this.html();
      };

      return Content;

    })();
    return exports.Content = Content;
  });

}).call(this);

/*
//@ sourceMappingURL=main.map
*/
