// Generated by CoffeeScript 1.6.2
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(function(require, exports, module) {
    var Content, SHContent;
    Content = require('content');
    SHContent = (function(_super) {
      __extends(SHContent, _super);

      function SHContent(streamhubContent) {
        if (typeof streamhubContent !== 'object' || !(streamhubContent.content && streamhubContent.content.bodyHtml)) {
          throw "Cannot create StreamHubContent without an object arg and arg.content.bodyHtml";
        }
        this._sh = streamhubContent;
      }

      SHContent.prototype.html = function(newVal) {
        if (newVal) {
          console.log("Warning: Can't set .html on StreamHubContent. It is derived");
          return false;
        }
        return this._sh.content.bodyHtml;
      };

      return SHContent;

    })(Content);
    return exports = SHContent;
  });

}).call(this);

/*
//@ sourceMappingURL=streamhub.content.map
*/
